/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repechajemv;

import Clases.Conexion;
import Clases.DetallePedido;
import Clases.Item;
import Clases.Pedido;
import Clases.Receta;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author TOSHIBA
 */
public class ActualizarPedido extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarPedido
     */
    
    Connection cnx;
    Pedido p;
    int nroFilas;
            
    public ActualizarPedido(Connection cnx) {
        initComponents();
        this.setTitle("Actualizar Pedido");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.cnx = cnx;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pActualizarPedido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bConsultarPedido = new javax.swing.JButton();
        bAgregarItem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetalle = new javax.swing.JTable();
        bCancelar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        txtNroMesa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Número de mesa");

        bConsultarPedido.setText("Consultar Pedido");
        bConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarPedidoActionPerformed(evt);
            }
        });

        bAgregarItem.setText("Agregar Item");
        bAgregarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarItemActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tbDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbDetalle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        txtNroMesa.setText("0");

        javax.swing.GroupLayout pActualizarPedidoLayout = new javax.swing.GroupLayout(pActualizarPedido);
        pActualizarPedido.setLayout(pActualizarPedidoLayout);
        pActualizarPedidoLayout.setHorizontalGroup(
            pActualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActualizarPedidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pActualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAgregarItem)
                    .addGroup(pActualizarPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bConsultarPedido))
                    .addGroup(pActualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pActualizarPedidoLayout.createSequentialGroup()
                            .addComponent(bCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bGuardar))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pActualizarPedidoLayout.setVerticalGroup(
            pActualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActualizarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pActualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bConsultarPedido)
                    .addComponent(txtNroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAgregarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pActualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bGuardar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pActualizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pActualizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void consultarReceta(String nombre){
        
        Item i = new Item(cnx);
        i.ObtenerDatos(nombre);
        Receta r = new Receta(cnx);
        r.obtenerDatos(i.getIdItem());
 
        JOptionPane.showMessageDialog(null,r.getDescripcion(), nombre, JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void AgregarItem(ArrayList<String> codigos,ArrayList<String> tipos,
            ArrayList<String> descripciones, ArrayList<String> cantidad){
        
        Object[][] datos = new Object[codigos.size()][5];
       
        for(int i = 0;i< codigos.size();i++){
            
            datos[i][0] = codigos.get(i);
            datos[i][1] = tipos.get(i);
            datos[i][2] = descripciones.get(i);
            datos[i][3] = new JButton("Consultar Receta");
            datos[i][4] = cantidad.get(i);
        }
        
        nroFilas = tbDetalle.getRowCount();
        DefaultTableModel modelo =  (DefaultTableModel) tbDetalle.getModel();
        
        for(int i = 0;i< codigos.size();i++){
            modelo.addRow(datos[i]);
        }
        
    }
    
    public void llenarTabla(ArrayList<String> codigos,ArrayList<String> tipos,
            ArrayList<String> descripciones, ArrayList<String> cantidad){
        
        String[] columnas = new String[]{"Código","Tipo","Descripción","Selecciona",
            "Cantidad"};
        
        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class,
            java.lang.String.class,
            java.lang.String.class,
            JButton.class,
            java.lang.Object.class 
        };
        /*       
        Object[][] datos = new Object[][]{
            {"code", "En", "Descripcion", new JButton("Consultar Receta"),"10"},
            {"code", "A", "Descripcion", new JButton("Consultar Receta"),"10"},
            {"code", "Ex", "Descripcion", new JButton("Consultar Receta"),"10"}
        };*/        
        Object[][] datos = new Object[codigos.size()][5];
       
        for(int i = 0;i< codigos.size();i++){
            
            datos[i][0] = codigos.get(i);
            datos[i][1] = tipos.get(i);
            datos[i][2] = descripciones.get(i);
            datos[i][3] = new JButton("Consultar Receta");
            datos[i][4] = cantidad.get(i);
        }

        tbDetalle.setModel(new javax.swing.table.DefaultTableModel(datos,columnas ){
            // Esta variable nos permite conocer de antemano los tipos de datos de cada columna, dentro del TableModel
            Class[] tipos = tiposColumnas;

            @Override
            public Class getColumnClass(int columnIndex) {
                // Este método es invocado por el CellRenderer para saber que dibujar en la celda,
                // observen que estamos retornando la clase que definimos de antemano.
                return tipos[columnIndex];
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                return !(this.getColumnClass(column).equals(JButton.class));
            }
        });
        
        tbDetalle.setDefaultRenderer(JButton.class, new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable jtable, Object objeto, boolean estaSeleccionado, boolean tieneElFoco, int fila, int columna) {
                /**
                 * Observen que todo lo que hacemos en éste método es retornar el objeto que se va a dibujar en la 
                 * celda. Esto significa que se dibujará en la celda el objeto que devuelva el TableModel. También 
                 * significa que este renderer nos permitiría dibujar cualquier objeto gráfico en la grilla, pues 
                 * retorna el objeto tal y como lo recibe.
                 */
                return (Component) objeto;
            }
        });
        
        tbDetalle.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tbDetalle.rowAtPoint(e.getPoint());
                int columna = tbDetalle.columnAtPoint(e.getPoint());

                /**
                 * Preguntamos si hicimos clic sobre la celda que contiene el botón, si tuviéramos más de un botón 
                 * por fila tendríamos que además preguntar por el contenido del botón o el nombre de la columna
                 */
                if (tbDetalle.getModel().getColumnClass(columna).equals(JButton.class)) {
                    
                    consultarReceta(String.valueOf(tbDetalle.getValueAt(fila,2)));
                    //JOptionPane.showMessageDialog(null, "Seleccionada la fila " + fila );
                }
            }
        });
        
        
        /*JButton boton = new JButton("Consultar Receta");
        boton.setSize(100,45);
        boton.setVisible(true);
        ActionListener listener = new ActionListener(){ 
           public void actionPerformed(ActionEvent e) { 
             consultarReceta(descripcion); //lo declaras en otra parte del documento
           }         
        };
        boton.addActionListener(listener);*/
        
    }
    
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarPedidoActionPerformed
        // TODO add your handling code here:
        
        ArrayList<String> codigos = new ArrayList();
        ArrayList<String> tipos = new ArrayList();
        ArrayList<String> descripciones = new ArrayList();
        ArrayList<String> cantidad = new ArrayList();
        
        p = new Pedido(cnx);
        p.ObtenerDatos(txtNroMesa.getText());
        
        DetallePedido oP = new DetallePedido(cnx);
        System.out.println(p.getIdPedido());
        ResultSet rs = oP.obtenerDetalle(p.getIdPedido());
         
        try {
            while(rs.next()){
                System.out.println("hola"+rs.getString(1));
                codigos.add(rs.getString(1));
                tipos.add(rs.getString(2));
                descripciones.add(rs.getString(3));
                cantidad.add(rs.getString(4));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        llenarTabla(codigos, tipos, descripciones, cantidad);
    }//GEN-LAST:event_bConsultarPedidoActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            for(int i=nroFilas;i<tbDetalle.getRowCount();i++){
                DetallePedido dP = new DetallePedido(Integer.valueOf(String.valueOf(tbDetalle.getValueAt(i, 0))), 
                        p.getIdPedido(), String.valueOf(tbDetalle.getValueAt(i, 4)), cnx);
                dP.almacenarDetalle(Integer.valueOf(String.valueOf(tbDetalle.getValueAt(i, 4))));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bAgregarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarItemActionPerformed
        // TODO add your handling code here:
        SeleccionarItem sI = new SeleccionarItem(cnx,this);
        sI.setVisible(true);
    }//GEN-LAST:event_bAgregarItemActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPedido().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarItem;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bConsultarPedido;
    private javax.swing.JButton bGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pActualizarPedido;
    private javax.swing.JTable tbDetalle;
    private javax.swing.JTextField txtNroMesa;
    // End of variables declaration//GEN-END:variables
}
